### ISSUE TITLE
failed to start on fedora 23 , maybe old node ...

### ISSUE THREAD

**Issue by ixasuhan** [techwizrd/GitKraken#36]
libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
Error: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/asuhan/gitkraken/resources/app.asar/node_modules/nodegit/dist/nodegit.js:11:12)
    at Object.<anonymous> (/home/asuhan/gitkraken/resources/app.asar/node_modules/nodegit/dist/nodegit.js:1025:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/asuhan/gitkraken/resources/app.asar/src/appBootstrap/upgradeScripts/versionScripts/v1_5_0.js:7:17)
    at Object.<anonymous> (/home/asuhan/gitkraken/resources/app.asar/src/appBootstrap/upgradeScripts/versionScripts/v1_5_0.js:298:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/asuhan/gitkraken/resources/app.asar/src/appBootstrap/upgradeScripts/versionScripts/index.js:5:28)
    at Object.<anonymous> (/home/asuhan/gitkraken/resources/app.asar/src/appBootstrap/upgradeScripts/versionScripts/index.js:14:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/asuhan/gitkraken/resources/app.asar/src/appBootstrap/upgradeScripts/index.js:7:24)
    at Object.<anonymous> (/home/asuhan/gitkraken/resources/app.asar/src/appBootstrap/upgradeScripts/index.js:43:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at App.module.exports.app.on (/home/asuhan/gitkraken/resources/app.asar/src/appBootstrap/main.js:174:5)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)

**Comment by sharikovvladislav** [comment]
Same problem on rh

**Comment by techwizrd** [comment]
This isn't Axosoft's GitKraken. I created this repository years before they published their application. It's an unfortunate name collision.
